#!/usr/bin/env bash
# this echoes "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each repeat.
# this displays  "I am invincible!!!" in between each repeat.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
