#!/usr/bin/env bash
# this writes to a string "I am alive" to the file /tmp/my_process.
# this stops two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
