#!/usr/bin/env bash
# this outputs numbers from 1 to 100 in list format.
# this outputs "FizzBuzz" when the number is a multiple of 3 and 5.
# this outputs "Fizz" when the number is a multiple of 3.
# this outputs "Buzz" when the number is a multiple of 5.
# Otherwise, displays the number.

for x in {1..100}
do
  if (( x % 3 == 0 && x % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( x % 3 == 0 ))
  then
    echo "Fizz"
  elif (( x % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$x"
  fi
done
