#!/usr/bin/env bash
# this echoes the contents of the file `/etc/passwd`.
# it shows only the username, user id, and user home dir path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
