#!/usr/bin/env bash
# this loops from 1 to 10 and echoes:
# "bad luck" on 4th iteration
# "good luck" on 8th iteration
# "Best School"on other iterations

cnt=0

while [$cnt -lt 10]
do
  if [$cnt -eq 3]
  then
    echo "bad luck"
  elif [$cnt -eq 7]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((cnt++))
done
