#!/usr/bin/env bash
# this echoes numbers btwn 1 to 20 combine wt:
# "bad luck from China" on the 4th iteration
# "bad luck from Japan" on 9th iteration
# "bad luck from Italy" on 17th loop iteration

cnt=1

while [ $cnt -le 20 ]
do
  echo "$cnt"
  case $cnt in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( cnt++ ))
done
