#!/usr/bin/env bash
# echoes time for 12 horus and 59 minutes.
# echoes hours from 0 to 12
# echoes minutes from 1 to 59

h=0

while [ $h -le 12 ]
do
  echo "Hour: $h"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( h++ ))
done
